### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by wangchengww** [moshi4/FastDTLmapper#68]
when I use the test example. I got the wrong info:
FileNotFoundError: [Errno 2] No such file or directory: 'output_minimum/02_dtl_reconciliation/OG0000000/treerecs/OG0000000_multifurcate.ufboot_recs.nwk'
How to solve this?

**Comment by moshi4** [comment]
Are you running FastDTLmapper with Docker?
If not, try Docker and you may be able to run it correctly.

If the error seems to occur even with Docker, can you upload the `log` directory that FastDTLmapper outputs to investigate the cause of the error?
